### ISSUE TITLE
Exceptions printing

### ISSUE THREAD

**Issue by Vladisl0ve** [alexmon1989/russia_ddos#13]
Application works, but sometimes creates exceptions.
Looks like that:
https://imgur.com/a/WSbcfqq

_Gif is too huge for Github, sorry_ 

Code of exceptions:
https://pastebin.com/hAgGBdcR
_Also there are a lot of rows for Github I think :D_

System: Ubuntu 21.04
Application version: latest (1.3.7)
Launched via Docker

**Comment by AlexNDRmac** [comment]
Hi @Vladisl0ve 
This error caused by some OS limits. I suggesting - you run it on macOS. So the Fix for this is very simple, see bellow:
```bash
# Check current system limits
ulimit -a

## You'll see output like this (macOS defaults)
core file size        (blocks, -c) 0
data seg size         (kbytes, -d) unlimited
file size             (blocks, -f) unlimited
max locked memory     (kbytes, -l) unlimited
max memory size       (kbytes, -m) unlimited
open files            (-n) 256
pipe size             (512 bytes, -p) 1
stack size            (kbytes, -s) 8192
cpu time              (seconds, -t) unlimited
max user processes    (-u) 2784
virtual memory        (kbytes, -v) unlimited


# Set new limit for 'open files'
ulimit -n 1200
```

After this changes script should be working without errors.

**Comment by Vladisl0ve** [comment]
I had limit == 1024
But I've changed to 2048 and now application works without exceptions.
Thank you
