### ISSUE TITLE
Different speed 

### ISSUE THREAD

**Issue by matherfather** [alexmon1989/russia_ddos#33]
HI guys.
I'm working via VPN and see different speed in network traffic (~20Mb/s) and VPN dashboard (843 Kb/s).
How it is possible? Do I flood own PC or? In original version speed is the same for network monitor and vpn.
I started with docker container and options from readme, only IP:port is deffierent 

Thx.

**Comment by AlexNDRmac** [comment]
VPN dashboard might show own speed. It's normal situation for VPN clients, especially for free VPN.
Try to read general info about VPN speed from CloudFlare ([link](https://www.cloudflare.com/learning/access-management/vpn-speed/))
